# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Experiences', folder: 'pages', file: 'experiences.html'}
- {name: 'Education', folder: 'pages', file: 'education.html'}
- {name: 'Projects', folder: 'pages', file: 'projects.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jianhli'}
- {icon: 'github-square', link: 'https://www.github.com/jian-hao-li'}
- {icon: 'envelope', link: 'mailto:jianhli@g.ucla.edu'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
